pipeline:

  init:
    image: chrisns/docker-terragrunt
    commands: terragrunt init
    environment:
      - TF_VAR_APPS_ID=${NOTPROD_ACC_ID}
      - TF_VAR_APPS_KEY=${NOTPROD_ACC_KEY}

  testsuite:
    image: quay.io/ukhomeofficedigital/dq-tf-testsuite:latest
    privileged: true
    pull: true
    commands: run

  validate:
    image: chrisns/docker-terragrunt
    pull: true
    commands: terragrunt validate
    environment:
      - TF_VAR_APPS_ID=${NOTPROD_ACC_ID}
      - TF_VAR_APPS_KEY=${NOTPROD_ACC_KEY}

  plan-notprod:
    image: chrisns/docker-terragrunt
    pull: true
    commands: terragrunt plan
    environment:
      - TF_VAR_APPS_ID=${NOTPROD_ACC_ID}
      - TF_VAR_APPS_KEY=${NOTPROD_ACC_KEY}

  graph-notprod:
    image: chrisns/docker-terragrunt
    pull: true
    commands: terragrunt graph
    environment:
      - TF_VAR_APPS_ID=${NOTPROD_ACC_ID}
      - TF_VAR_APPS_KEY=${NOTPROD_ACC_KEY}

  apply-notprod:
    image: chrisns/docker-terragrunt
    pull: true
    commands: terragrunt apply -auto-approve
    environment:
      - TF_VAR_APPS_ID=${NOTPROD_ACC_ID}
      - TF_VAR_APPS_KEY=${NOTPROD_ACC_KEY}
    when:
      branch: master

## production
  init:
    image: chrisns/docker-terragrunt
    commands: terragrunt init -reconfigure
    environment:
      - NAMESPACE=prod
      - TF_VAR_APPS_ID=${PROD_ACC_ID}
      - TF_VAR_APPS_KEY=${PROD_ACC_KEY}
    when:
      event: [deployment, push]

  apply-prod:
    image: chrisns/docker-terragrunt
    pull: true
    commands: terragrunt apply -auto-approve
    environment:
      - NAMESPACE=prod
      - TF_VAR_APPS_ID=${PROD_ACC_ID}
      - TF_VAR_APPS_KEY=${PROD_ACC_KEY}
    when:
      event: deployment