pipeline:

  init:
    image: chrisns/docker-terragrunt
    pull: true
    commands:
      - export TF_VAR_APPS_ID=${NOTPROD_ACC_ID}
      - export TF_VAR_APPS_KEY=${NOTPROD_ACC_KEY}
      - terragrunt init

  testsuite:
    image: quay.io/ukhomeofficedigital/dq-tf-testsuite:latest
    privileged: true
    commands: run
    when:
      branch:
        exclude: [ master ]

  validate:
    image: chrisns/docker-terragrunt
    commands:
      - export TF_VAR_APPS_ID=${NOTPROD_ACC_ID}
      - export TF_VAR_APPS_KEY=${NOTPROD_ACC_KEY}
      - terragrunt validate
    when:
      branch:
        exclude: [ master ]

  plan-notprod:
    image: chrisns/docker-terragrunt
    commands:
      - export TF_VAR_APPS_ID=${NOTPROD_ACC_ID}
      - export TF_VAR_APPS_KEY=${NOTPROD_ACC_KEY}
      - terragrunt plan -lock=false -out=plan
    when:
      event: push

  apply-notprod:
    image: chrisns/docker-terragrunt
    commands:
      - export TF_VAR_APPS_ID=${NOTPROD_ACC_ID}
      - export TF_VAR_APPS_KEY=${NOTPROD_ACC_KEY}
      - terragrunt apply -auto-approve -parallelism=50 plan
    when:
      branch: master
      event: push


## production
  init-prod:
    image: chrisns/docker-terragrunt
    commands:
      - export TF_VAR_APPS_ID=${PROD_ACC_ID}
      - export TF_VAR_APPS_KEY=${PROD_ACC_KEY}
      - terragrunt init -reconfigure
    environment:
      - TF_VAR_NAMESPACE=prod
    when:
      event: [deployment, push]

  plan-prod:
    image: chrisns/docker-terragrunt
    commands:
      - export TF_VAR_APPS_ID=${PROD_ACC_ID}
      - export TF_VAR_APPS_KEY=${PROD_ACC_KEY}
      - terragrunt plan -lock=false -out=prodplan
    environment:
      - TF_VAR_NAMESPACE=prod
    when:
      event: [deployment, push]

  apply-prod:
    image: chrisns/docker-terragrunt
    commands:
      - export TF_VAR_APPS_ID=${PROD_ACC_ID}
      - export TF_VAR_APPS_KEY=${PROD_ACC_KEY}
      - terragrunt apply -auto-approve -parallelism=50 prodplan
    environment:
      - TF_VAR_NAMESPACE=prod
    when:
      environment: prod
      event: deployment