pipeline:

  init:
    image: chrisns/docker-terragrunt
    commands:
      - terragrunt init

  testsuite:
    image: quay.io/ukhomeofficedigital/dq-tf-testsuite:latest
    privileged: true
    commands: run

  validate:
    image: chrisns/docker-terragrunt
    commands:
      - terragrunt validate

  plan:
    image: chrisns/docker-terragrunt
    commands:
      - terragrunt plan

  graph:
    image: chrisns/docker-terragrunt
    commands:
      - terragrunt graph

  apply:
    image: chrisns/docker-terragrunt
    commands:
      - terragrunt apply -auto-approve
    when:
      branch: master

#  clean_up:
#    image: chrisns/docker-terragrunt
#    commands:
#      - terragrunt destroy -force
#    when:
#      status: [ failure, success ]
#      branch: master