pipeline:

  init:
    image: chrisns/docker-terragrunt
    pull: true
    commands:
      - export TF_VAR_APPS_ID=$${NOTPROD_ACC_ID}
      - export TF_VAR_APPS_KEY=$${NOTPROD_ACC_KEY}
      - terragrunt init
    secrets:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - NOTPROD_ACC_ID
      - NOTPROD_ACC_KEY

  testsuite:
    image: docker:18.05
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker run --rm -v $(pwd):/data -w /data hashicorp/terraform fmt --diff --check
    when:
      branch:
        exclude: [ master ]
    secrets:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - NOTPROD_ACC_ID
      - NOTPROD_ACC_KEY

  validate:
    image: chrisns/docker-terragrunt
    commands:
      - export TF_VAR_APPS_ID=$${NOTPROD_ACC_ID}
      - export TF_VAR_APPS_KEY=$${NOTPROD_ACC_KEY}
      - export MOCK_ID=$${TF_VAR_MOCK_ID}
      - export MOCK_KEY=$${TF_VAR_MOCK_KEY}
      - export CI_ID=$${AWS_ACCESS_KEY_ID}
      - export CI_KEY=$${AWS_SECRET_ACCESS_KEY}
      - terragrunt validate
    when:
      branch:
        exclude: [ master ]
    secrets:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - NOTPROD_ACC_ID
      - NOTPROD_ACC_KEY
      - TF_VAR_MOCK_ID
      - TF_VAR_MOCK_KEY  

  plan-notprod:
    image: chrisns/docker-terragrunt
    commands:
      - export TF_VAR_APPS_ID=$${NOTPROD_ACC_ID}
      - export TF_VAR_APPS_KEY=$${NOTPROD_ACC_KEY}
      - export MOCK_ID=$${TF_VAR_MOCK_ID}
      - export MOCK_KEY=$${TF_VAR_MOCK_KEY}
      - export CI_ID=$${AWS_ACCESS_KEY_ID}
      - export CI_KEY=$${AWS_SECRET_ACCESS_KEY}
      - terragrunt plan -lock=false -out=plan
    when:
      event: push
    secrets:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - NOTPROD_ACC_ID
      - NOTPROD_ACC_KEY
      - TF_VAR_MOCK_ID
      - TF_VAR_MOCK_KEY

  apply-notprod:
    image: chrisns/docker-terragrunt
    commands:
      - export TF_VAR_APPS_ID=$${NOTPROD_ACC_ID}
      - export TF_VAR_APPS_KEY=$${NOTPROD_ACC_KEY}
      - export MOCK_ID=$${TF_VAR_MOCK_ID}
      - export MOCK_KEY=$${TF_VAR_MOCK_KEY}
      - export CI_ID=$${AWS_ACCESS_KEY_ID}
      - export CI_KEY=$${AWS_SECRET_ACCESS_KEY}
      - terragrunt apply -auto-approve -parallelism=50 plan
    when:
      branch: master
      event: push
    secrets:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - NOTPROD_ACC_ID
      - NOTPROD_ACC_KEY
      - TF_VAR_MOCK_ID
      - TF_VAR_MOCK_KEY


## production
  init-prod:
    image: chrisns/docker-terragrunt
    commands:
      - export TF_VAR_APPS_ID=$${PROD_ACC_ID}
      - export TF_VAR_APPS_KEY=$${PROD_ACC_KEY}
      - terragrunt init -reconfigure
    environment:
      - TF_VAR_NAMESPACE=prod
    when:
      event: [deployment, push]
    secrets:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - PROD_ACC_ID
      - PROD_ACC_KEY

  plan-prod:
    image: chrisns/docker-terragrunt
    commands:
      - export TF_VAR_APPS_ID=$${PROD_ACC_ID}
      - export TF_VAR_APPS_KEY=$${PROD_ACC_KEY}
      - terragrunt plan -lock=false -out=prodplan
    environment:
      - TF_VAR_NAMESPACE=prod
    when:
      event: [deployment, push]
    secrets:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - PROD_ACC_ID
      - PROD_ACC_KEY

  apply-prod:
    image: chrisns/docker-terragrunt
    commands:
      - export TF_VAR_APPS_ID=$${PROD_ACC_ID}
      - export TF_VAR_APPS_KEY=$${PROD_ACC_KEY}
      - terragrunt apply -auto-approve -parallelism=50 prodplan
    environment:
      - TF_VAR_NAMESPACE=prod
    when:
      environment: prod
      event: deployment
    secrets:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - PROD_ACC_ID
      - PROD_ACC_KEY
