pipeline:

  init:
    image: chrisns/docker-terragrunt
    commands:
      - export TF_VAR_APPS_ID=${NOTPROD_ACC_ID}
      - export TF_VAR_APPS_KEY=${NOTPROD_ACC_KEY}
      - terragrunt init

  testsuite:
    image: quay.io/ukhomeofficedigital/dq-tf-testsuite:latest
    privileged: true
    pull: true
    commands: run

  validate:
    image: chrisns/docker-terragrunt
    pull: true
    commands:
      - export TF_VAR_APPS_ID=${NOTPROD_ACC_ID}
      - export TF_VAR_APPS_KEY=${NOTPROD_ACC_KEY}
      - terragrunt validate

  plan-notprod:
    image: chrisns/docker-terragrunt
    pull: true
    commands:
      - export TF_VAR_APPS_ID=${NOTPROD_ACC_ID}
      - export TF_VAR_APPS_KEY=${NOTPROD_ACC_KEY}
      - terragrunt plan -lock=false

  graph-notprod:
    image: chrisns/docker-terragrunt
    pull: true
    commands:
      - export TF_VAR_APPS_ID=${NOTPROD_ACC_ID}
      - export TF_VAR_APPS_KEY=${NOTPROD_ACC_KEY}
      - terragrunt graph

  apply-notprod:
    image: chrisns/docker-terragrunt
    pull: true
    commands:
      - export TF_VAR_APPS_ID=${NOTPROD_ACC_ID}
      - export TF_VAR_APPS_KEY=${NOTPROD_ACC_KEY}
      - terragrunt apply -auto-approve
    when:
      branch: master

## production
  init:
    image: chrisns/docker-terragrunt
    commands:
      - export TF_VAR_APPS_ID=${PROD_ACC_ID}
      - export TF_VAR_APPS_KEY=${PROD_ACC_KEY}
      - terragrunt init -reconfigure
    environment:
      - NAMESPACE=prod
    when:
      event: [deployment, push]

  plan:
    image: chrisns/docker-terragrunt
    commands:
      - export TF_VAR_APPS_ID=${PROD_ACC_ID}
      - export TF_VAR_APPS_KEY=${PROD_ACC_KEY}
      - terragrunt plan -lock=false
    environment:
      - NAMESPACE=prod
    when:
      event: [deployment, push]

  apply-prod:
    image: chrisns/docker-terragrunt
    pull: true
    commands:
      - export TF_VAR_APPS_ID=${PROD_ACC_ID}
      - export TF_VAR_APPS_KEY=${PROD_ACC_KEY}
      - terragrunt apply -auto-approve
    environment:
      - NAMESPACE=prod
    when:
      event: deployment